### ISSUE TITLE
Horizontal regression

### ISSUE THREAD

**Issue by RosaWagner** [huertatipografica/Andada#10]
Same reason as vertical regression, the corrected spacing is very different from previous published version, which result in a big line-length and paragraph-length difference (even if it is indeed better).

cc @davelab6 for confirmation (in case it would be okay).

![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/12222436/116420971-bc912680-a83e-11eb-9efa-6d4c9e790d09.gif)

**Comment by CaroGiovagnoli** [comment]
Same #9

**Comment by davelab6** [comment]
I propose we publish this on GF as a new family `Andada Pro` to free up all regression constraints
