### ISSUE TITLE
Non orthogonal design space

### ISSUE THREAD

**Issue by RosaWagner** [huertatipografica/Andada#8]
Regular master is at `100` but Regular instance is at `96`.
Extreme master is at `140` but ExtraBold instance is at `135`.

We need a consistent designspace for the font to export a VF with proper AVAR and STAT table. At least one master (preferably Regular) has to be the same as an existing instance of the FVAR table. To solve this, we can create a new regular master from the instance at `96`, which would become the main/origin master of the font.

OR you actually don't want to export a variable font, and in that case we don't care ;)

**Comment by CaroGiovagnoli** [comment]
Hi, 
I think that we can create a new Regular master from the instance at `96` and also an ExtraBold at `140`.

(I'd like to preserve the Regular color)

**Comment by RosaWagner** [comment]
Do you want to keep the 100 master after that?
(removing it would save some file size)

**Comment by CaroGiovagnoli** [comment]
i don't want to keep the `100` master.
