### ISSUE TITLE
Vertical regression

### ISSUE THREAD

**Issue by RosaWagner** [huertatipografica/Andada#9]
We can't serve an update which has different vertical metrics from previous published version. It would mess up too much webpages.

We also need` typoLinegap = hheaLineGap = 0`.

**Previous:**
![Capture d’écran 2021-04-27 à 16 29 17](https://user-images.githubusercontent.com/12222436/116273992-88f0c680-a782-11eb-80f0-6590a3289c7d.png)

**New:** 
![Capture d’écran 2021-04-27 à 16 28 46](https://user-images.githubusercontent.com/12222436/116259262-f3e7d080-a775-11eb-9e5d-7d26d8cec2fa.png)

**Current diff:**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/12222436/116259713-550fa400-a776-11eb-8cf9-2cbf77d33803.gif)

**Comment by CaroGiovagnoli** [comment]
How can I get your version to compare with my version? 
It's difficult to see with this animated gif in detail.
Thanks, Caro

**Comment by RosaWagner** [comment]
I updated the screenshot of v-matrics values, I had put 2 times the same. 

I am comparing the version published on google fonts: https://fonts.google.com/specimen/Andada
with your actual version that is in the PR #11

**Comment by CaroGiovagnoli** [comment]
The metrics and the weights are different now. 
The new regular and bold are lighter and there are more weights available, I've had added intermediate weights, Medium, and ExtraBold.

I think that given that this won’t be 100% backward compatible, then it’s better to fix the vertical metrics now. 
Better to break things for better just once :)

**Comment by RosaWagner** [comment]
I know this is annoying, but there are reasons for these specifications. The first one is that Andada is served to several thousands of websites, and we can't break thousands of websites without upsetting as many web designers and developers. 

Also, LineGap is not supported consistently across platform. Some applications are adding this space under the descender, some don't add this space at all. Web browsers share this space above the ascender, and under the descender. We need linegap value to 0 to ensure consistent start baseline and linespacing in different environments.

Good news is, WinAscent and WinDescent are used to match Y-max and Y-min to avoid text clipping, and since we activate the use_typo_metric flags, it is okay for those value to change.
